[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vote_solb = "9VSCLy3hTLydi6igAGVbDE2yPapv1t4PW4QH7btBsj26"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sss/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
