[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_escrow = "BeiFzCRT6F7isRsKQHyTTLARxPNVBnvP5WzFY6K1BRjY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sss/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
